### ISSUE TITLE
UI doesn't update properly when switching to an empty category

### ISSUE THREAD

**Issue by Itschotsch** [Daniele122898/media-dashboard#3]
Steps to reproduce:
1. Create a category "A" from a non-empty folder.
2. Create a category "B" from an empty folder.
3. Select "A".
4. Select "B". **The UI will still show the contents of "A".**

Example with non-empty folders "Wahrscheinlichkeit und Statistik" and "Introduction To Machine Learning" and empty folder "Formal Methods and Functional Programming":
https://imgur.com/c9o0IZH

**Comment by Daniele122898** [comment]
cant reproduce on current version
